### ISSUE TITLE
in histc wrong names

### ISSUE THREAD

**Issue by carbuz** [maxto/ubique#7]
in histc function the freq field is not the frequency (a percentage of the total number of observations) but the count of the observation in a particlar interval. Could you please change it? maybe you can create an object like this {bins: ..., count:..., freq:...}
i.e in your code at line 74 in histc.js substitute
out.push({bins: y[k],  freq: h[k]})
with 
out.push({bins: y[k], count: h[k], freq: h[k]/a.length})

Thanks

**Comment by maxto** [comment]
Solved https://github.com/maxto/ubique/blob/master/doc/stats/histc.md
